# Generated by Django 2.2.12 on 2021-09-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210925_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.CharField(default='Anonymus', max_length=255, verbose_name='Текст'),
        ),
    ]
