# Generated by Django 2.2.12 on 2021-09-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210927_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.CharField(default='Anonymus', max_length=10, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст'),
        ),
    ]
