# Generated by Django 2.2.12 on 2021-09-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210927_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
    ]
