# Generated by Django 2.2.12 on 2021-09-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210927_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.CharField(default='Anonymus', max_length=255, verbose_name='Автор'),
        ),
    ]
